#!/bin/bash

#exit on fail
set -e

repodir="/home/ubuntu/krow/KrowAlpha"
installdir="/home/ubuntu/composer/"

port="3000"
version=openssl rand -base64 5

[ -n "$1" ] && port="$1"

cd "$repodir"
git pull

cd krow

tmp=$(mktemp)
jq '.version = "$version"' package.json > "$tmp" && mv "$tnp" package.json

cd ..

cp "$repodir"/scripts/composer/* "$installdir" || true

cd "krow"
logger "HLFC: Updating network card..."
composer archive create -t dir -n .
composer network install -c PeerAdmin@hlfv1 -a krow@$version.bna
composer network upgrade -c PeerAdmin@hlfv1 -n krow -V $version

logger "HLFC: Starting REST server..."
"$installdir"/stopserver
"$installdir"/startserver "$port"
