#!/bin/bash

repodir="/home/ubuntu/krow/KrowAlpha"
dockerdir="$repodir/composer"
composerdir="$repodir/krow"
installdir="/home/ubuntu/composer/"

cd "$installdir"/fabric-tools
sudo ./startFabric.sh

cd "$dockerdir"
sudo docker-compose start

cd "$installdir"/fabric-tools
./createPeerAdminCard.sh

cd "$composerdir"
composer archive create -t dir -n .
composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName krow
composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile krow@0.0.1.bna --file networkadmin.card

screen -X -S composer-rest-server quit 2>/dev/null || true
screen -dm -S composer-rest-server composer-rest-server -c admin@krow -n never -w true -p "$port"
