#!/bin/bash

repodir="/home/ubuntu/krow/KrowAlpha"
dockerdir="$repodir/composer"
installdir="/home/ubuntu/composer/"

branch="master"
port="3000"

[ -n "$1" ] && branch="$1"
[ -n "$2" ] && port="$2"

cd "$dockerdir"
logger "HLFC: Starting docker-compose..."
sudo docker-compose start

cd "$repodir"
git checkout "$branch"

logger "HLFC: Starting REST server..."
"$installdir"/stopserver
"$installdir"/startserver "$port"

logger "HLFC: Started REST server."
