#!/bin/bash

port="3000"

[ -n "$1" ] && port="$1"

screen -dm -S composer-rest-server composer-rest-server -y 43a444f1-1ce9-4fcc-8508-cb0cbb4272e0 -c admin@krow -n never -w true -p "$port"

#alternative
#composer-rest-server -c admin@krow -n never -w true -p "$port" >/dev/null 2>&1 &
