#!/bin/bash

port="3000"

[ -n "$1" ] && port="$1"

screen -dm -S composer-rest-server composer-rest-server -y qLBrEwIv690nAbMfVHB965WC3KfoC1VpvkBjDUiBfVOG5mTzlUlwkckKLerAUxxv -c admin@krow -n never -w true -p "$port"

#alternative
#composer-rest-server -c admin@krow -n never -w true -p "$port" >/dev/null 2>&1 &
