#!/bin/bash

repodir="/home/ubuntu/krow/KrowAlpha"
dockerdir="$repodir/composer"
installdir="/home/ubuntu/composer/"

logger "HLFC: Stopping REST server..."
"$installdir"/stopserver

logger "HLFC: Stopped REST server."

cd "$dockerdir"
logger "HLFC: Stopping Fabric..."
sudo docker-compose stop

logger "HLFC: Stopped Fabric."
