#!/bin/bash

#exit on fail
set -e

repodir="/home/ubuntu/krow/KrowAlpha"
token="ff7210fe63d1593df37e7fe01653ad46dc706377"

repository=${REPOSITORY-"KrowNetwork/KrowAlpha.git"}
branch="master"
port="3000"

[ -n "$1" ] && branch="$1"
[ -n "$2" ] && port="$2"

cd "$repodir"
git pull https://"$token"@github.com/"$repository"
[ "$branch" = "master" ] || git checkout "$branch"

cd "krow"
composer archive create -t dir -n .
composer network update -c admin@krow -a krow@0.0.1.bna

screen -X -S composer-rest-server quit 2>/dev/null || true
screen -dm -S composer-rest-server composer-rest-server -c admin@krow -n never -w true -p "$port"
